#!bin/bash

sudo apt-get install software-properties-common

sudo add-apt-repository ppa:gluster/glusterfs-7 -y
sudo apt-get update

sudo apt-get install glusterfs-server -y

sudo systemctl start glusterd && sudo systemctl enable glusterd











