#!bin/sh

echo "-----------------"
docker network create --driver=overlay traefik-public
if [ $? -eq 0 ]; then
    echo "traefik-public network created"
else
    echo "creating network traefik-public has failed"
fi

echo "-----------------"
export NODE_ID=$(docker info -f '{{.Swarm.NodeID}}')
echo "exported NODE_ID"

echo "-----------------"
docker node update --label-add traefik-public.traefik-public-certificates=true $NODE_ID
if [ $? -eq 0 ]; then
    echo "traefik bonded to this node succesfully"
else
    echo "bonding traefik has failed"
    exit
fi


echo "-----------------"
read -p "email for let's encrypt: " email
export EMAIL=$email
echo "email exported"

echo "-----------------"
read -p "domain for web interface: " domain
export DOMAIN=$domain
echo "domain exported succesfully"

echo "-----------------"
read -p "username for web interface: " username
export USERNAME=$username
echo "username exported succesfully"


echo "-----------------"
read -sp "password for web interface: " pswd
export PASSWORD=$pswd
echo "password exported succesfully"

echo "-----------------"
export HASHED_PASSWORD=$(openssl passwd -apr1 $PASSWORD)
echo "hashed_password exported succesfully"

echo "-----------------"
sudo mkdir -p /data/traefik
sudo curl -L https://raw.githubusercontent.com/yahatsuki/compose/main/traefik-swarm -o /data/traefik/traefik.yml
if [ $? -eq 0 ]; then
    echo "compose-file downloaded to /data/traefik/traefik.yml succesfully"
else
    echo "downloading compose-file has failed"
    exit
fi


echo "-----------------"
docker stack deploy -c /data/traefik/traefik.yml traefik
if [ $? -eq 0 ]; then
    echo "traefik deployed on this swarm succesfully"
else
    echo "deploying traefik has failed"
    exit
fi

echo "-----------------"
echo "waiting for stack to come online"
sleep 60
docker stack ps traefik

