#!bin/sh

docker network create --driver=overlay traefik-public

export NODE_ID=$(docker info -f '{{.Swarm.NodeID}}')

docker node update --label-add traefik-public.traefik-public-certificates=true $NODE_ID

echo "---------------------------------------------------"
echo
echo -n "Email for Let's Encrypt?"
read $email
export EMAIL=$email

echo "---------------------------------------------------"
echo
echo -n "Domain for Web Interface?"
read $domain
export DOMAIN=$domain

echo "---------------------------------------------------"
echo
echo -n "Username for Web Interface?"
read $username
export USERNAME=$username

echo "---------------------------------------------------"
echo
echo -n "Password for Web Interface?"
read $password
export PASSWORD=$password

export HASHED_PASSWORD=$(openssl passwd -apr1 $PASSWORD)

curl -L https://raw.githubusercontent.com/yahatsuki/compose/traefik-swarm -o traefik.yml

docker stack deploy -c traefik.yml traefik
